// Application, FPC & Lazarus Version Information

const
  { The default Free Pascal Compiler }
  FPC_VERSION='3.3.1';
  FPC_TARGET='x86_64';

  { Source & Subversion Last Changed Commit }
  SOURCE_VERSION='0.1.1.62';
  SOURCE_REVISION='268';
  SOURCE_URL='http://github.com/shidel/fd-nls-utils';
  SOURCE_ONLINE='';
  SOURCE_COMMIT='c3989bdc40567a3e4e11dc767694edf1780261cd';

  { Version Build Atributes } 
  BUILD_DEBUG=False;
  BUILD_PRERELEASE=False;
  BUILD_PATCHED=False;
  BUILD_PRIVATE=False;
  BUILD_SPECIAL=False;
  BUILD_LANGUAGE='';
  BUILD_CHARSET='';
  BUILD_DATE='2022-03-20 19:49:49';

  { General Application Information }
  APP_IDENTIFIER='com.jeromeshidel.fd-nls';
  APP_VERSION='0.1.1.62';
  APP_COMMENTS='FreeDOS NLS Desktop Utility';
  APP_COMPANYNAME='Jerome Shidel';
  APP_FILEDESCRIPTION='FreeDOS NLS Desktop Utility';
  APP_INTERNALNAME='FD-NLS';
  APP_LEGALCOPYRIGHT='2022 Jerome Shidel';
  APP_ORIGINALFILENAME='FD-NLS';
  APP_PRODUCTNAME='FD-NLS';
  APP_PRODUCTVERSION='1.0';
  APP_YEAR='2022';

